[tool.poetry]
name = "manim-mohrsCircle"
version = "0.1.5"
description = "A plugin that allows for the animation of the method-based creation of Mohr's Circle diagrams."
license = "MIT"
authors = ["Jordan Senft"]
readme = "README.md"
classifiers= [
    "Development Status :: 4 - Beta",
    "License :: OSI Approved :: MIT License",
    "Topic :: Scientific/Engineering",
    "Topic :: Multimedia :: Video",
    "Topic :: Multimedia :: Graphics",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
	"Programming Language :: Python :: 3.9",
    "Natural Language :: English",
]

[tool.poetry.dependencies]
python = "^3.6.2"
manim = ">=0.3"

[tool.poetry.plugins."manim.plugins"]
mohrscircle = "manim_mohrscircle"
[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"